### ISSUE TITLE
Chore: Move Content Script Register Into Manifest

### ISSUE THREAD

**Issue by cdrani** [cdrani/yqm#11]
Move `registerScript` logic out of service worker (background.js) and move into `manifest.json`

https://github.com/cdrani/yqm/blob/b81f870a08b105ab2d6a4f6c137aa50fcaa2dcdc/background.js#L24-L31

Reference how it's done here: https://github.com/cdrani/chorus/blob/9f07fd960e1742c18cc7dec1054466203543f99d/manifest.json#L16-L23
```json
"content_scripts": [
    {
        "run_at": "document_idle",
        "js": ["utils/state.js", "content-script.js"],
        "css": ["styles.css"],
        "matches": ["*://open.spotify.com/*"]
    }
 ],
```

**Comment by snazzyai** [comment]
I would like to help with this issue if that is okay.
